# docker-compose.yml
services:  # <-- KEY: Defines the services block Translated comment

  flask_app: # <-- Service 1, indented under services Translated comment
    build: .
    container_name: my_flask_ong_app
    ports:
      - "5001:5000"
    volumes:
      - ./ong_app:/app/ong_app
      - ./run.py:/app/run.py
      # - ./requirements.txt:/app/requirements.txt # We can comment this if it doesn't change Translated comment
    environment:
       # Tells Flask where to find the factory Translated comment
      - FLASK_APP=ong_app:create_app 
       # Activates dev mode (debug and reloader) Translated comment
      - FLASK_ENV=development        
       
      - SECRET_KEY=my_super_secret_from_compose_123! 
      # Odoo Variables Translated comment
      - ODOO_URL=http://odoo:8069
      - ODOO_DB=ong_db
      - ODOO_USER=miguel.romero.3@etu.unige.ch
      - ODOO_PASSWORD=simplepassword
    depends_on:
      - odoo
    networks:
       # Add it to the custom network Translated comment
      - ong_network 

  odoo: # <-- Service 2, indented under services (same level as flask_app) Translated comment
    image: odoo:16.0
    container_name: odoo_service
    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
    volumes:
       # Named volume Translated comment
      - odoo_data:/var/lib/odoo 
    environment:
      - HOST=odoo_db
      - PORT=5432
      - USER=odoo
       # Odoo DB connection password (defined below) Translated comment
      - PASSWORD=odoo_password 
       
      # - ODOO_MASTER_PASSWORD=3hbh-nbcc-ht99 
    networks:
      # Add it to the custom network Translated comment
      - ong_network 

  odoo_db: # <-- Service 3, indented under services (same level as flask_app) Translated comment
    image: postgres:15
    container_name: odoo_postgres_db
    environment:
      - POSTGRES_DB=postgres
       # IMPORTANT!! Same password Odoo uses to connect Translated comment
      - POSTGRES_PASSWORD=odoo_password 
       # IMPORTANT!! Same user Odoo uses to connect Translated comment
      - POSTGRES_USER=odoo            
    volumes:
      # Named volume Translated comment
      - postgres_data:/var/lib/postgresql/data 
    networks:
      # Add it to the custom network Translated comment
      - ong_network 

# --- Named Volumes (Top Level) --- Translated comment
volumes: # <-- Same level as 'services' Translated comment
  odoo_data:
  postgres_data:

# --- Custom Network (Top Level) --- Translated comment
networks: # <-- Same level as 'services' Translated comment
  ong_network:
    driver: bridge